import {Card} from "../cards";

export const CARDS: Card[] = [
  { id: 1, title: 'ausserHaus', category: "kommunikation",
    text: "Gehe aus dem Haus und spreche mit Menschen über dein Produkt",
    img: "chatbubbles", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 2, title: 'chatten', category: "kommunikation",
    text: "Kommuniziere nur per Chat und Email",
    img: "mail", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 3, title: 'nichtchatten', category: "kommunikation",
    text: "Kommuniziere ohne Chat und Email",
    img: "mail", history: ['02-1-2018', "06-2-2018"],

  },
  { id: 4, title: 'spaziergang', category: "kommunikation",
    text: "Mache einen Spaziergang mit einem Kollegen",
    img: "walk", history: ['02-1-2018', "06-2-2018"],

  },
  { id: 5, title: 'englisch', category: "kommunikation",
    text: "Sprich nur Englisch",
    img: "chatbubbles", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 6, title: 'vortrag', category: "kommunikation",
    text: "Halte einen Vortrag",
    img: "megaphone", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 7, title: 'reimen', category: "kommunikation",
    text: "Sprich nur in Reimen",
    img: "chatbubbles", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 8, title: 'meetings', category: "kommunikation",  //
    text: "Sag alle deine Meetings für den Tag ab",
    img: "chatbubbles", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 9, title: 'remote', category: "arbeitsplatz",
    text: "Arbeite spontan einen Tag von Remote",
    img: "headset", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 10, title: 'aufstehen', category: "arbeitsplatz",
    text: "Arbeite einen Tag lang im Stehen",
    img: "body", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 11, title: 'hinlegen', category: "arbeitsplatz",
    text: "Lege dich zum Nachdenken hin",
    img: "body", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 12, title: 'andererRaum', category: "arbeitsplatz",
    text: "Arbeite einen Tag lang in einem anderen Raum",
    img: "door", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 13, title: 'rausAusBuero', category: "arbeitsplatz",
    text: "Raus aus dem Büro! (kein Homeoffice)",
    img: "briefcase", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 14, title: 'tauschen', category: "arbeitsplatz",
    text: "Tausche mit einem Kollegen (aus einem anderen Team) die Arbeit!",
    img: "sync", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 15, title: 'tauschen', category: "bleibTapfer",
    text: "Lösche alles, was du gestern entwickelt hast und schreibe es neu",
    img: "trash", history: ['02-1-2018', "06-2-2018"],

  },
  { id: 16, title: 'tauschen', category: "bleibTapfer",  //
    text: "Lasse den Fenstermanager zu und erledige alles über die Konsole",
    img: "chatbubbles", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 17, title: 'tauschen', category: "bleibTapfer",
    text: "Arbeite einen Tag lang ohne IDE, nur mit Texteditor und Shell",
    img: "brush", history: ['02-1-2018', "06-2-2018"],

  },
  { id: 18, title: 'tauschen', category: "bleibTapfer",
    text: "Trinke einen Tag lang keinen Kaffee/Tee",
    img: "cafe", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 19, title: 'tauschen', category: "bleibTapfer",
    text: "Konsumiere keine Süßigkeiten",
    img: "ice-cream", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 20, title: 'tauschen', category: "bleibTapfer",
    text: "Übernimm eine Aufgabe, die Du noch nie wahrgenommen hast.",
    img: "clipboard", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 21, title: 'tauschen', category: "bleibTapfer",
    text: "Iss heute fünf Portionen Obst",
    img: "nutrition", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 22, title: 'tauschen', category: "informationsbeschaffung", //
    text: "Gehe einen Tag lang nicht auf Stackoverflow",
    img: "chatbubbles", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 23, title: 'tauschen', category: "informationsbeschaffung",
    text: "Suche einen Tag lang Lösungen nicht im Internet sondern frage Kollegen oder Bücher um Rat",
    img: "person", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 24, title: 'slackAtack', category: "joker",
    text: "Slack-Atack",
    img: "trophy", history: ['02-1-2018', "06-2-2018"],
  },
  { id: 25, title: 'mittagessen', category: "Perspektivwechsel",
    text: "Esse an einem Dir unbekannten Ort zu Mittag",
    img: "restaurant", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 26, title: 'umweg', category: "Perspektivwechsel",
    text: "Nimm einen Weg nach Hause, den du sonst nie gehst.",
    img: "walk", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 27, title: 'rentner', category: "Perspektivwechsel",
    text: "Erkläre einem älteren Verwandten woran du gerade arbeitest.",
    img: "person", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 28, title: 'kind', category: "Perspektivwechsel",
    text: "Erläre einem Kind woran du gerade arbeitest.",
    img: "person", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 29, title: 'nachbar', category: "Perspektivwechsel",
    text: "Klingel bei den Nachbarn und biete deine Hilfe an",
    img: "help-circle", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 31, title: 'sprache', category: "Arbeitsmittel",
    text: "Ändere die Sprache deiner Tastatur",
    img: "settings", history: ['02-1-2018', "06-2-2018"]
  }
  { id: 31, title: 'progsprache', category: "Arbeitsmittel",
    text: "Arbeite in einer anderen Programmiersprache",
    img: "quote", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 32, title: 'maus', category: "Arbeitsmittel",
    text: "Arbeite ohne Alt + Tab",
    img: "chatbubbles", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 33, title: 'maus', category: "Arbeitsmittel",
    text: "Arbeite heute ohne Maus",
    img: "hand", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 34, title: 'maus', category: "Arbeitsmittel",
    text: "Tippe mit nur einer Hand",
    img: "hand", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 35, title: 'stift', category: "Arbeitsmittel",
    text: "Arbeite nur mit Stift und Papier",
    img: "create", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 36, title: 'internet', category: "Arbeitsmittel",
    text: "Arbeite ohne Internetverbindung",
    img: "globe", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 37, title: 'maus', category: "Arbeitsmittel",
    text: "Nutze die Maus mit der ungewohnten Hand",
    img: "hand", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 38, title: 'maus', category: "Arbeitsmittel",
    text: "Arbeite ohne Computer",
    img: "power", history: ['02-1-2018', "06-2-2018"]
  },
  { id: 39, title: 'maus', category: "Arbeitsmittel",
    text: "Arbeite nur mit dem Notebookmonitor",
    img: "desktop", history: ['02-1-2018', "06-2-2018"]
  }
];


